import type { ResourceConfig } from "@/components/admin/ResourceManager";

const publishedField = {
  name: "published",
  label: "Published",
  type: "boolean" as const,
  inTable: true,
};

const sortField = { name: "sort_order", label: "Sort order", type: "number" as const };

export const companiesConfig: ResourceConfig = {
  table: "companies",
  title: "Group companies",
  singular: "Company",
  description:
    "Every company page on the site is rendered from this content, in English and Arabic.",
  slugFrom: "name_en",
  ordering: true,
  searchColumns: ["name_en", "code", "slug"],
  orderBy: [{ column: "sort_order", ascending: true }],
  fields: [
    { name: "code", label: "Short code", type: "text", required: true, inTable: true },
    { name: "name_en", label: "Name (EN)", type: "text", required: true, inTable: true },
    { name: "name_ar", label: "Name (AR)", type: "text" },
    {
      name: "slug",
      label: "Page slug",
      type: "text",
      help: "e.g. nxtlevvel-biochem",
      inTable: true,
    },
    { name: "tag_en", label: "Tagline (EN)", type: "text" },
    { name: "tag_ar", label: "Tagline (AR)", type: "text" },
    {
      name: "description_en",
      label: "Short description (EN)",
      type: "textarea",
      rows: 3,
      full: true,
    },
    {
      name: "description_ar",
      label: "Short description (AR)",
      type: "textarea",
      rows: 3,
      full: true,
    },
    { name: "logo_url", label: "Logo", type: "image", folder: "companies" },
    { name: "hero_image", label: "Hero image", type: "image", folder: "companies" },
    { name: "gallery", label: "Gallery images", type: "images", folder: "companies" },
    { name: "overview_en", label: "Overview (EN)", type: "textarea", rows: 6, full: true },
    { name: "overview_ar", label: "Overview (AR)", type: "textarea", rows: 6, full: true },
    { name: "vision_en", label: "Vision (EN)", type: "textarea", rows: 3, full: true },
    { name: "vision_ar", label: "Vision (AR)", type: "textarea", rows: 3, full: true },
    { name: "mission_en", label: "Mission (EN)", type: "textarea", rows: 3, full: true },
    { name: "mission_ar", label: "Mission (AR)", type: "textarea", rows: 3, full: true },
    {
      name: "technology_en",
      label: "Technology & capability (EN)",
      type: "textarea",
      rows: 4,
      full: true,
    },
    {
      name: "technology_ar",
      label: "Technology & capability (AR)",
      type: "textarea",
      rows: 4,
      full: true,
    },
    { name: "products_en", label: "Products (EN)", type: "tags", help: "Comma separated" },
    { name: "products_ar", label: "Products (AR)", type: "tags", help: "Comma separated" },
    { name: "applications_en", label: "Applications (EN)", type: "tags", help: "Comma separated" },
    { name: "applications_ar", label: "Applications (AR)", type: "tags", help: "Comma separated" },
    {
      name: "leadership_en",
      label: "Leadership (EN)",
      type: "textarea",
      rows: 4,
      full: true,
      help: "One person per line: Name | Role | Short bio",
    },
    {
      name: "leadership_ar",
      label: "Leadership (AR)",
      type: "textarea",
      rows: 4,
      full: true,
      help: "One person per line: Name | Role | Short bio",
    },
    { name: "contact_email", label: "Contact email", type: "text" },
    { name: "contact_phone", label: "Contact phone", type: "text" },
    { name: "contact_address_en", label: "Address (EN)", type: "textarea", rows: 2, full: true },
    { name: "contact_address_ar", label: "Address (AR)", type: "textarea", rows: 2, full: true },
    { name: "cta_en", label: "Call to action (EN)", type: "text" },
    { name: "cta_ar", label: "Call to action (AR)", type: "text" },
    { name: "seo_title", label: "SEO title", type: "text", full: true },
    { name: "seo_description", label: "Meta description", type: "textarea", rows: 3, full: true },
    { name: "og_image", label: "Social share image", type: "image", folder: "companies" },
    { name: "keywords", label: "Keywords", type: "text", full: true },
    { name: "featured", label: "Featured", type: "boolean" },
    publishedField,
    sortField,
  ],
};

export const projectsConfig: ResourceConfig = {
  table: "projects",
  title: "Projects",
  singular: "Project",
  description: "Portfolio of delivered and ongoing engineering projects.",
  slugFrom: "name",
  ordering: true,
  searchColumns: ["name", "client", "location"],
  orderBy: [
    { column: "sort_order", ascending: true },
    { column: "created_at", ascending: false },
  ],
  fields: [
    { name: "name", label: "Project name", type: "text", required: true, inTable: true },
    { name: "client", label: "Client", type: "text", inTable: true },
    {
      name: "company_code",
      label: "Group company",
      type: "text",
      help: "Short code of the delivering company, e.g. TIPCO or NXTLEVVEL BIOCHEM",
      inTable: true,
    },
    { name: "industry", label: "Industry", type: "text", inTable: true },
    { name: "location", label: "Location", type: "text" },
    { name: "year", label: "Year", type: "number" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: ["Completed", "Ongoing", "Upcoming"],
      inTable: true,
    },
    { name: "services", label: "Services", type: "tags", help: "Comma separated" },
    { name: "technologies", label: "Technologies", type: "tags", help: "Comma separated" },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "cover_image", label: "Cover image", type: "image", folder: "projects" },
    { name: "images", label: "Gallery images", type: "images", folder: "projects" },
    {
      name: "brochure_url",
      label: "Brochure (PDF)",
      type: "file",
      bucket: "documents",
      folder: "projects",
    },
    { name: "featured", label: "Featured", type: "boolean" },
    publishedField,
    sortField,
  ],
};

export const newsConfig: ResourceConfig = {
  table: "news",
  title: "News & media",
  singular: "Article",
  slugFrom: "title",
  searchColumns: ["title", "category"],
  orderBy: [{ column: "published_at", ascending: false }],
  fields: [
    { name: "title", label: "Title", type: "text", required: true, inTable: true },
    { name: "category", label: "Category", type: "text", inTable: true },
    { name: "published_at", label: "Publish date", type: "date", inTable: true },
    { name: "excerpt", label: "Excerpt", type: "textarea", rows: 3, full: true },
    { name: "body", label: "Body", type: "textarea", rows: 12, full: true },
    { name: "cover_image", label: "Cover image", type: "image", folder: "news" },
    publishedField,
    sortField,
  ],
};

export const jobsConfig: ResourceConfig = {
  table: "jobs",
  title: "Careers",
  singular: "Vacancy",
  slugFrom: "position",
  ordering: true,
  searchColumns: ["position", "department", "location"],
  orderBy: [
    { column: "sort_order", ascending: true },
    { column: "created_at", ascending: false },
  ],
  fields: [
    { name: "position", label: "Position", type: "text", required: true, inTable: true },
    { name: "department", label: "Department", type: "text", inTable: true },
    {
      name: "employment_type",
      label: "Employment type",
      type: "select",
      options: ["Full time", "Contract", "Part time", "Internship"],
      inTable: true,
    },
    { name: "location", label: "Location", type: "text", inTable: true },
    { name: "experience", label: "Experience", type: "text" },
    { name: "closing_date", label: "Closing date", type: "date" },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "responsibilities", label: "Responsibilities", type: "textarea", full: true },
    { name: "requirements", label: "Requirements", type: "textarea", full: true },
    publishedField,
    sortField,
  ],
};

export const applicationsConfig: ResourceConfig = {
  table: "job_applications",
  title: "Job applications",
  singular: "Application",
  readOnly: true,
  searchColumns: ["full_name", "email"],
  orderBy: [{ column: "created_at", ascending: false }],
  fields: [
    { name: "full_name", label: "Applicant", type: "text", inTable: true },
    { name: "email", label: "Email", type: "text", inTable: true },
    { name: "phone", label: "Phone", type: "text", inTable: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: ["new", "shortlisted", "interviewing", "rejected", "hired"],
      inTable: true,
    },
    { name: "message", label: "Message", type: "textarea", full: true },
    { name: "cv_url", label: "CV", type: "file", bucket: "documents", folder: "cv" },
  ],
  filters: [
    {
      column: "status",
      label: "statuses",
      options: ["new", "shortlisted", "interviewing", "rejected", "hired"],
    },
  ],
};

export const productsConfig: ResourceConfig = {
  table: "products",
  title: "Products & services",
  singular: "Entry",
  slugFrom: "name",
  ordering: true,
  searchColumns: ["name", "category"],
  orderBy: [
    { column: "sort_order", ascending: true },
    { column: "created_at", ascending: false },
  ],
  filters: [{ column: "kind", label: "types", options: ["product", "service"] }],
  fields: [
    { name: "name", label: "Name", type: "text", required: true, inTable: true },
    {
      name: "kind",
      label: "Type",
      type: "select",
      options: ["product", "service"],
      required: true,
      inTable: true,
    },
    { name: "category", label: "Category", type: "text", inTable: true },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "cover_image", label: "Cover image", type: "image", folder: "products" },
    { name: "images", label: "Gallery", type: "images", folder: "products" },
    {
      name: "datasheet_url",
      label: "Datasheet",
      type: "file",
      bucket: "documents",
      folder: "products",
    },
    {
      name: "brochure_url",
      label: "Brochure",
      type: "file",
      bucket: "documents",
      folder: "products",
    },
    { name: "featured", label: "Featured", type: "boolean" },
    publishedField,
    sortField,
  ],
};

export const certificatesConfig: ResourceConfig = {
  table: "certificates",
  title: "Certificates",
  singular: "Certificate",
  ordering: true,
  searchColumns: ["name", "category"],
  orderBy: [
    { column: "sort_order", ascending: true },
    { column: "issue_date", ascending: false },
  ],
  fields: [
    { name: "name", label: "Certificate name", type: "text", required: true, inTable: true },
    { name: "category", label: "Category", type: "text", inTable: true },
    { name: "issue_date", label: "Issue date", type: "date", inTable: true },
    { name: "expiry_date", label: "Expiry date", type: "date", inTable: true },
    { name: "preview_image", label: "Preview image", type: "image", folder: "certificates" },
    {
      name: "pdf_url",
      label: "Certificate PDF",
      type: "file",
      bucket: "documents",
      folder: "certificates",
    },
    publishedField,
    sortField,
  ],
};

export const galleryAlbumsConfig: ResourceConfig = {
  table: "gallery_albums",
  title: "Gallery albums",
  singular: "Album",
  slugFrom: "title",
  ordering: true,
  searchColumns: ["title", "category"],
  orderBy: [{ column: "sort_order", ascending: true }],
  fields: [
    { name: "title", label: "Album title", type: "text", required: true, inTable: true },
    { name: "category", label: "Category", type: "text", inTable: true },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "cover_image", label: "Cover image", type: "image", folder: "gallery" },
    publishedField,
    sortField,
  ],
};

export const clientLogosConfig: ResourceConfig = {
  table: "client_logos",
  title: "Client logos",
  singular: "Client",
  ordering: true,
  searchColumns: ["name"],
  orderBy: [{ column: "sort_order", ascending: true }],
  fields: [
    { name: "name", label: "Client name", type: "text", required: true, inTable: true },
    { name: "logo_url", label: "Logo", type: "image", folder: "clients", required: true },
    { name: "website", label: "Website", type: "text", inTable: true },
    publishedField,
    sortField,
  ],
};

export const statsConfig: ResourceConfig = {
  table: "site_stats",
  title: "Website statistics",
  singular: "Statistic",
  ordering: true,
  orderBy: [{ column: "sort_order", ascending: true }],
  fields: [
    { name: "label", label: "Label", type: "text", required: true, inTable: true },
    { name: "value", label: "Value", type: "number", required: true, inTable: true },
    { name: "suffix", label: "Suffix", type: "text", inTable: true, placeholder: "+" },
    publishedField,
    sortField,
  ],
};

export const enquiriesConfig: ResourceConfig = {
  table: "contact_enquiries",
  title: "Contact enquiries",
  singular: "Enquiry",
  readOnly: true,
  searchColumns: ["name", "email", "company", "subject"],
  orderBy: [{ column: "created_at", ascending: false }],
  fields: [
    { name: "name", label: "Name", type: "text", inTable: true },
    { name: "email", label: "Email", type: "text", inTable: true },
    { name: "company", label: "Company", type: "text", inTable: true },
    { name: "subject", label: "Subject", type: "text", inTable: true },
    { name: "is_read", label: "Read", type: "boolean", inTable: true },
    { name: "phone", label: "Phone", type: "text" },
    { name: "message", label: "Message", type: "textarea", rows: 8, full: true },
  ],
};

export const seoConfig: ResourceConfig = {
  table: "seo_settings",
  title: "SEO settings",
  singular: "Route",
  searchColumns: ["route", "title"],
  orderBy: [{ column: "route", ascending: true }],
  fields: [
    {
      name: "route",
      label: "Route",
      type: "text",
      required: true,
      inTable: true,
      placeholder: "/projects",
    },
    { name: "title", label: "Meta title", type: "text", inTable: true },
    { name: "description", label: "Meta description", type: "textarea", full: true },
    { name: "keywords", label: "Keywords", type: "text" },
    { name: "og_image", label: "OG image", type: "image", folder: "seo" },
    { name: "noindex", label: "No-index", type: "boolean", inTable: true },
  ],
};
